### PR TITLE
fixed compilation issues for TrueStudio 8.1

### PR DESCRIPTION
**Pull request by vkomenda**
The TrueStudio configuration in the current master does not compile. I fixed all the compilation issues in this patch.

### CODE REVIEW

**Comment by teomaras76** [comment]
Hi Vladimir,
thanks a lot for the patch for TrueStudio environment, very appreciated! Give me few time to re-check it before merging it officially in the base branch.

**Comment by teomaras76** [comment]
I rechecked with latest version of Atollic TrueStudio for STM32 version 9.0 and I did not face any issue of compilation as you reported (without any modification from Github repository).
I see you are using 8.1 version, if possible can you try to upgrade to new 9.0 version and re-check?

**Comment by teomaras76** [comment]
@vkomenda please may you kindly give a feedback if you have tyried Truestudio version 9.0 and if current FW version ok for you to compile?

**Comment by vkomenda** [comment]
Hi Matteo. Sorry for the delay. I was busy and will try version 9.0 now.

**Comment by vkomenda** [comment]
Checked. There are no such issues in v9.

**Pull request closed without merging**
